_format_version: "1.1"
services:
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: true
  - name: rest
    url: http://rest:3000
    routes:
      - name: rest-route
        paths:
          - /rest/v1
        strip_path: true
  - name: storage
    url: http://storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage/v1
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - FORCE_CORS_ORIGIN_REFLECTION
        - ACCEPT
        - ACCEPT-VERSION
        - CONTENT-LENGTH
        - CONTENT-MD5
        - CONTENT-TYPE
        - DATE
        - X-AUTH-TOKEN
        - X-REQUESTED-WITH
        - APIKEY
        - AUTHORIZATION
        - X-CLIENT-INFO
        - X-SUPABASE-API-VERSION
      exposed_headers:
        - "*"
      credentials: true
      max_age: 3600
