_format_version: "1.1"
services:
  - name: public
    routes:
      - name: auth
        paths:
          - /auth/v1
        strip_path: true
        service: auth
      - name: rest
        paths:
          - /rest/v1
        strip_path: true
        service: rest

  - name: auth
    url: http://auth:9999
  - name: rest
    url: http://rest:3000
